//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotenBu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Permissions()
        {
            this.T_Permissions1 = new HashSet<T_Permissions>();
            this.T_UserGroup = new HashSet<T_UserGroup>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
        public Nullable<System.Guid> FK_ParentID { get; set; }
        public string Code { get; set; }
        public string Ico { get; set; }
        public string Introduction { get; set; }
        public int Ranks { get; set; }
        public bool IfEnable { get; set; }
        public bool IfDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Permissions> T_Permissions1 { get; set; }
        public virtual T_Permissions T_Permissions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UserGroup> T_UserGroup { get; set; }
    }
}
