//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotenBu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_User()
        {
            this.T_Token = new HashSet<T_Token>();
            this.T_UserGroup = new HashSet<T_UserGroup>();
        }
    
        public System.Guid ID { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string WeChatOpenID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string HeadPortrait { get; set; }
        public string TrueName { get; set; }
        public string NickName { get; set; }
        public byte RegisterSources { get; set; }
        public byte Sex { get; set; }
        public bool IfEnable { get; set; }
        public bool IfDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Token> T_Token { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UserGroup> T_UserGroup { get; set; }
    }
}
